# Generated by Django 4.0.1 on 2022-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(max_length=1000)),
                ('hash', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
